import 'package:google_mlkit_pose_detection/google_mlkit_pose_detection.dart';
import 'base_pattern.dart';
import 'squat_pattern.dart';
import 'step_up_pattern.dart';
import 'push_pattern.dart';
import 'pull_pattern.dart';
import 'hinge_pattern.dart';
import 'curl_pattern.dart';
import 'knee_drive_pattern.dart';
import 'hold_pattern.dart';
import 'rotation_pattern.dart';
import 'calf_pattern.dart';
import 'piston_pattern.dart';
import 'core_pattern.dart';
enum PatternType { squat, stepUp, push, pull, hinge, curl, kneeDrive, hold, rotation, calf, piston, core }
class ExerciseConfig {
  final PatternType patternType;
  final Map<String, dynamic> params;
  const ExerciseConfig({required this.patternType, this.params = const {}});
}
class MovementEngine {
  BasePattern? _activePattern;
  BasePattern? get activePattern => _activePattern;
  String? _currentExerciseId;
  int get repCount => _activePattern?.repCount ?? 0;
  String get feedback => _activePattern?.feedback ?? '';
  double get chargeProgress => _activePattern?.chargeProgress ?? 0;
  bool get justHitTrigger => _activePattern?.justHitTrigger ?? false;
  bool get isLocked => _activePattern?.isLocked ?? false;
  RepState get state => _activePattern?.state ?? RepState.ready;
  String? get currentExerciseId => _currentExerciseId;
  void setExercise(String exerciseId) {
    _currentExerciseId = exerciseId.toLowerCase().replaceAll(' ', '_').replaceAll('-', '_');
    final config = exercises[_currentExerciseId];
    if (config == null) { _activePattern = SquatPattern(); return; }
    _activePattern = _createPattern(config);
  }
  void loadExercise(String exerciseId) => setExercise(exerciseId);
  static bool hasPattern(String exerciseId) {
    final normalized = exerciseId.toLowerCase().replaceAll(' ', '_').replaceAll('-', '_');
    return exercises.containsKey(normalized);
  }
  void captureBaseline(dynamic landmarks) {
    if (_activePattern == null) return;
    if (landmarks is List<PoseLandmark>) {
      final map = {for (var lm in landmarks) lm.type: lm};
      _activePattern!.captureBaseline(map);
    } else if (landmarks is Map<PoseLandmarkType, PoseLandmark>) {
      _activePattern!.captureBaseline(landmarks);
    }
  }
  bool processFrame(dynamic landmarks) {
    if (_activePattern == null) return false;
    if (landmarks is List<PoseLandmark>) {
      final map = {for (var lm in landmarks) lm.type: lm};
      return _activePattern!.processFrame(map);
    } else if (landmarks is Map<PoseLandmarkType, PoseLandmark>) {
      return _activePattern!.processFrame(landmarks);
    }
    return false;
  }
  void reset() { _activePattern?.reset(); }
  BasePattern _createPattern(ExerciseConfig config) {
    switch (config.patternType) {
      case PatternType.squat:
        return SquatPattern(triggerPercent: config.params['triggerPercent'] ?? 0.78, resetPercent: config.params['resetPercent'] ?? 0.92, cueGood: config.params['cueGood'] ?? 'Depth!', cueBad: config.params['cueBad'] ?? 'Lower!');
      case PatternType.stepUp:
        return StepUpPattern(cueGood: config.params['cueGood'] ?? 'Up!', cueBad: config.params['cueBad'] ?? 'Drive!');
      case PatternType.push:
        return PushPattern(inverted: config.params['inverted'] ?? false, cueGood: config.params['cueGood'] ?? (config.params['inverted'] == true ? 'Lockout!' : 'Push!'), cueBad: config.params['cueBad'] ?? (config.params['inverted'] == true ? 'Press higher!' : 'Chest down!'));
      case PatternType.pull:
        return PullPattern(triggerPercent: config.params['triggerPercent'] ?? 0.55, resetPercent: config.params['resetPercent'] ?? 0.85, cueGood: config.params['cueGood'] ?? 'Pull!', cueBad: config.params['cueBad'] ?? 'Higher!');
      case PatternType.hinge:
        return HingePattern(inverted: config.params['inverted'] ?? false, floor: config.params['floor'] ?? false, triggerPercent: config.params['triggerPercent'] ?? 0.55, resetPercent: config.params['resetPercent'] ?? 0.85, cueGood: config.params['cueGood'] ?? 'Squeeze!', cueBad: config.params['cueBad'] ?? 'Hips!');
      case PatternType.curl:
        return CurlPattern(cueGood: config.params['cueGood'] ?? 'Squeeze!', cueBad: config.params['cueBad'] ?? 'Full range!');
      case PatternType.kneeDrive:
        return KneeDrivePattern(mode: config.params['mode'] ?? KneeDriveMode.verticalKnee, cueGood: config.params['cueGood'] ?? 'Drive!', cueBad: config.params['cueBad'] ?? 'Higher!', triggerThreshold: config.params['triggerThreshold'], resetThreshold: config.params['resetThreshold']);
      case PatternType.hold:
        return HoldPattern(holdType: config.params['holdType'] ?? HoldType.plank, cueGood: config.params['cueGood'] ?? 'Hold!', cueBad: config.params['cueBad'] ?? 'Stay tight!');
      case PatternType.rotation:
        return RotationPattern(cueGood: config.params['cueGood'] ?? 'Rotate!', cueBad: config.params['cueBad'] ?? 'Control!');
      case PatternType.calf:
        return CalfPattern(cueGood: config.params['cueGood'] ?? 'Up!', cueBad: config.params['cueBad'] ?? 'Higher!');
      case PatternType.piston:
        return PistonPattern(cueGood: config.params['cueGood'] ?? 'Push!', cueBad: config.params['cueBad'] ?? 'Control!');
      case PatternType.core:
        return CorePattern(trackingMode: config.params['trackingMode'] ?? 'noseRise', triggerThreshold: config.params['triggerThreshold'] ?? 10.0, resetThreshold: config.params['resetThreshold'] ?? 2.0, cueGood: config.params['cueGood'] ?? 'Crunch!', cueBad: config.params['cueBad'] ?? 'Higher!');
    }
  }
  static const Map<String, ExerciseConfig> exercises = {
    // ═══════════════════════════════════════════════════════════════════════
    // SQUAT PATTERN — GIF KEYS
    // ═══════════════════════════════════════════════════════════════════════
    'barbell_full_squat': ExerciseConfig(patternType: PatternType.squat),
    'barbell_front_squat': ExerciseConfig(patternType: PatternType.squat),
    'barbell_front_chest_squat': ExerciseConfig(patternType: PatternType.squat),
    'barbell_bench_front_squat': ExerciseConfig(patternType: PatternType.squat),
    'barbell_bench_squat': ExerciseConfig(patternType: PatternType.squat),
    'barbell_high_bar_squat': ExerciseConfig(patternType: PatternType.squat),
    'barbell_low_bar_squat': ExerciseConfig(patternType: PatternType.squat),
    'barbell_low_bar_squat_with_rack': ExerciseConfig(patternType: PatternType.squat),
    'barbell_olympic_squat': ExerciseConfig(patternType: PatternType.squat),
    'barbell_full_zercher_squat': ExerciseConfig(patternType: PatternType.squat),
    'barbell_sumo_squat': ExerciseConfig(patternType: PatternType.squat),
    'dumbbell_squat': ExerciseConfig(patternType: PatternType.squat),
    'dumbbell_goblet_squat': ExerciseConfig(patternType: PatternType.squat),
    'dumbbell_bench_squat': ExerciseConfig(patternType: PatternType.squat),
    'dumbbell_sumo_squat': ExerciseConfig(patternType: PatternType.squat),
    'smith_squat': ExerciseConfig(patternType: PatternType.squat),
    'smith_squat_to_bench': ExerciseConfig(patternType: PatternType.squat),
    'smith_front_squat': ExerciseConfig(patternType: PatternType.squat),
    'smith_front_squat_clean_grip': ExerciseConfig(patternType: PatternType.squat),
    'smith_frankenstein_squat': ExerciseConfig(patternType: PatternType.squat),
    'smith_zercher_squat': ExerciseConfig(patternType: PatternType.squat),
    'smith_low_bar_squat': ExerciseConfig(patternType: PatternType.squat),
    'smith_chair_squat': ExerciseConfig(patternType: PatternType.squat),
    'lever_squat_plate_loaded': ExerciseConfig(patternType: PatternType.squat),
    'lever_full_squat': ExerciseConfig(patternType: PatternType.squat),
    'lever_seated_squat': ExerciseConfig(patternType: PatternType.squat),
    'lever_chair_squat': ExerciseConfig(patternType: PatternType.squat),
    'lever_pistol_squat': ExerciseConfig(patternType: PatternType.squat),
    'lever_deadlift_plate_loaded': ExerciseConfig(patternType: PatternType.squat),
    'sled_full_hack_squat': ExerciseConfig(patternType: PatternType.squat),
    'sled_hack_squat': ExerciseConfig(patternType: PatternType.squat),
    'squat_m': ExerciseConfig(patternType: PatternType.squat),
    'sit_squat': ExerciseConfig(patternType: PatternType.squat),
    'resistance_band_squat': ExerciseConfig(patternType: PatternType.squat),
    'barbell_deadlift': ExerciseConfig(patternType: PatternType.squat),
    'barbell_romanian_deadlift': ExerciseConfig(patternType: PatternType.squat),
    'barbell_stiff_leg_deadlift': ExerciseConfig(patternType: PatternType.squat),
    'barbell_sumo_deadlift': ExerciseConfig(patternType: PatternType.squat),
    'dumbbell_romanian_deadlift': ExerciseConfig(patternType: PatternType.squat),
    'dumbbell_stiff_leg_deadlift': ExerciseConfig(patternType: PatternType.squat),
    'dumbbell_single_leg_deadlift': ExerciseConfig(patternType: PatternType.squat),
    'smith_deadlift': ExerciseConfig(patternType: PatternType.squat),
    'smith_stiff_legged_deadlift': ExerciseConfig(patternType: PatternType.squat),
    'lever_leg_extension': ExerciseConfig(patternType: PatternType.squat, params: {'cueGood': 'Squeeze!', 'cueBad': 'Full extension!'}),
    'lever_alternate_leg_extension_plate_loaded': ExerciseConfig(patternType: PatternType.squat, params: {'cueGood': 'Squeeze!', 'cueBad': 'Full extension!'}),
    'lever_lying_leg_curl': ExerciseConfig(patternType: PatternType.squat, params: {'cueGood': 'Squeeze!', 'cueBad': 'Full curl!'}),
    'lever_seated_leg_curl': ExerciseConfig(patternType: PatternType.squat, params: {'cueGood': 'Squeeze!', 'cueBad': 'Full curl!'}),
    'lever_kneeling_leg_curl_plate_loaded': ExerciseConfig(patternType: PatternType.squat),
    'inverse_leg_curl_on_pull_up_cable_machine': ExerciseConfig(patternType: PatternType.squat),
    'barbell_quarter_squat': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.85}),
    'barbell_one_leg_squat': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.70}),
    'single_leg_squat_with_support_pistol': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.70}),
    'barbell_lunge': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.78, 'resetPercent': 0.88}),
    'barbell_rear_lunge': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.78, 'resetPercent': 0.88}),
    'dumbbell_lunge': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.78, 'resetPercent': 0.88}),
    'dumbbell_rear_lunge': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.78, 'resetPercent': 0.88}),
    'dumbbell_curtsy_lunge': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.78, 'resetPercent': 0.88}),
    'dumbbell_single_leg_split_squat': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.78, 'resetPercent': 0.88}),
    'dumbbell_bulgarian_split_squat': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.78, 'resetPercent': 0.88}),
    'smith_single_leg_split_squat': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.78, 'resetPercent': 0.88}),
    'smith_split_squat': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.78, 'resetPercent': 0.88}),
    'split_squats': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.78, 'resetPercent': 0.88}),
    'walking_lunge_male': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.78, 'resetPercent': 0.88}),
    'barbell_lateral_lunge': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.80, 'resetPercent': 0.88}),
    'barbell_side_split_squat_ii': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.80, 'resetPercent': 0.88}),
    'dumbbell_lateral_lunge': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.80, 'resetPercent': 0.88}),
    'lever_leg_press': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.75}),
    'lever_seated_leg_press': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.75}),
    'sled_45_degree_leg_press': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.75}),
    'sled_45_degree_leg_wide_press': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.75}),
    'sled_45_degree_narrow_stance_leg_press': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.75}),
    'sled_lying_leg_press': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.75}),
    'sled_lying_squat': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.75}),
    'sled_reverse_hack_squat': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.75}),
    'smith_leg_press': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.75}),
    'jump_squat': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.80}),
    'box_jump_with_jump': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.80}),
    'dumbbell_step_up': ExerciseConfig(patternType: PatternType.stepUp, params: {'cueGood': 'Up!', 'cueBad': 'Drive!'}),
    // ═══════════════════════════════════════════════════════════════════════
    // PUSH PATTERN — GIF KEYS
    // ═══════════════════════════════════════════════════════════════════════
    'push_up_m': ExerciseConfig(patternType: PatternType.push),
    'wide_hand_push_up': ExerciseConfig(patternType: PatternType.push),
    'push_up_on_forearms': ExerciseConfig(patternType: PatternType.push),
    'incline_reverse_grip_push_up': ExerciseConfig(patternType: PatternType.push),
    'decline_push_up_m': ExerciseConfig(patternType: PatternType.push),
    'diamond_push_up': ExerciseConfig(patternType: PatternType.push),
    'close_grip_push_up': ExerciseConfig(patternType: PatternType.push),
    'pike_push_up': ExerciseConfig(patternType: PatternType.push),
    'barbell_bench_press': ExerciseConfig(patternType: PatternType.push),
    'barbell_incline_bench_press': ExerciseConfig(patternType: PatternType.push),
    'barbell_decline_bench_press': ExerciseConfig(patternType: PatternType.push),
    'barbell_close_grip_bench_press': ExerciseConfig(patternType: PatternType.push),
    'barbell_incline_close_grip_bench_press': ExerciseConfig(patternType: PatternType.push),
    'barbell_reverse_close_grip_bench_press': ExerciseConfig(patternType: PatternType.push),
    'barbell_incline_reverse_grip_press': ExerciseConfig(patternType: PatternType.push),
    'barbell_incline_wide_reverse_grip_bench_press': ExerciseConfig(patternType: PatternType.push),
    'barbell_decline_wide_grip_press': ExerciseConfig(patternType: PatternType.push),
    'barbell_lying_close_grip_press': ExerciseConfig(patternType: PatternType.push),
    'barbell_reverse_grip_decline_bench_press': ExerciseConfig(patternType: PatternType.push),
    'barbell_reverse_grip_incline_bench_press': ExerciseConfig(patternType: PatternType.push),
    'dumbbell_bench_press': ExerciseConfig(patternType: PatternType.push),
    'dumbbell_incline_bench_press': ExerciseConfig(patternType: PatternType.push),
    'dumbbell_decline_bench_press': ExerciseConfig(patternType: PatternType.push),
    'dumbbell_decline_hammer_press': ExerciseConfig(patternType: PatternType.push),
    'dumbbell_palms_in_incline_bench_press': ExerciseConfig(patternType: PatternType.push),
    'dumbbell_reverse_bench_press': ExerciseConfig(patternType: PatternType.push),
    'smith_bench_press': ExerciseConfig(patternType: PatternType.push),
    'smith_incline_bench_press': ExerciseConfig(patternType: PatternType.push),
    'smith_decline_bench_press': ExerciseConfig(patternType: PatternType.push),
    'smith_close_grip_bench_press': ExerciseConfig(patternType: PatternType.push),
    'smith_wide_grip_bench_press': ExerciseConfig(patternType: PatternType.push),
    'smith_wide_grip_decline_bench_press': ExerciseConfig(patternType: PatternType.push),
    'smith_incline_reverse_grip_press': ExerciseConfig(patternType: PatternType.push),
    'smith_decline_reverse_grip_press': ExerciseConfig(patternType: PatternType.push),
    'smith_reverse_grip_press': ExerciseConfig(patternType: PatternType.push),
    'smith_machine_decline_close_grip_bench_press': ExerciseConfig(patternType: PatternType.push),
    'smith_machine_reverse_decline_close_grip_bench_press': ExerciseConfig(patternType: PatternType.push),
    'cable_bench_press': ExerciseConfig(patternType: PatternType.push),
    'cable_incline_bench_press': ExerciseConfig(patternType: PatternType.push),
    'cable_decline_press': ExerciseConfig(patternType: PatternType.push),
    'lever_chest_press': ExerciseConfig(patternType: PatternType.push),
    'lever_chest_press_plate_loaded': ExerciseConfig(patternType: PatternType.push),
    'lever_chest_press_version_2': ExerciseConfig(patternType: PatternType.push),
    'lever_chest_press_version_4': ExerciseConfig(patternType: PatternType.push),
    'lever_incline_chest_press': ExerciseConfig(patternType: PatternType.push),
    'lever_incline_hammer_chest_press': ExerciseConfig(patternType: PatternType.push),
    'lever_decline_chest_press': ExerciseConfig(patternType: PatternType.push),
    'lever_decline_chest_press_version_2': ExerciseConfig(patternType: PatternType.push),
    'lever_parallel_chest_press': ExerciseConfig(patternType: PatternType.push),
    'lever_pec_deck_fly': ExerciseConfig(patternType: PatternType.push),
    'dumbbell_fly': ExerciseConfig(patternType: PatternType.push),
    'dumbbell_incline_fly': ExerciseConfig(patternType: PatternType.push),
    'dumbbell_decline_fly': ExerciseConfig(patternType: PatternType.push),
    'cable_fly': ExerciseConfig(patternType: PatternType.push),
    'cable_incline_fly': ExerciseConfig(patternType: PatternType.push),
    'cable_decline_fly': ExerciseConfig(patternType: PatternType.push),
    'cable_low_fly': ExerciseConfig(patternType: PatternType.push),
    'cable_middle_fly': ExerciseConfig(patternType: PatternType.push),
    'cable_lying_fly': ExerciseConfig(patternType: PatternType.push),
    'cable_crossover_variation': ExerciseConfig(patternType: PatternType.push),
    'cable_upper_chest_crossovers': ExerciseConfig(patternType: PatternType.push),
    'butterfly_machine': ExerciseConfig(patternType: PatternType.push),
    // OHP (inverted)
    'barbell_standing_military_press': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'barbell_standing_close_grip_military_press': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'barbell_seated_behind_head_military_press': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'barbell_seated_military_press_inside_squat_cage': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'dumbbell_seated_shoulder_press': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'dumbbell_standing_overhead_press': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'dumbbell_arnold_press': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'dumbbell_arnold_press_ii': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'dumbbell_bench_seated_press': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'smith_shoulder_press': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'smith_standing_military_press': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'smith_standing_behind_head_military_press': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'smith_behind_neck_press': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'smith_seated_shoulder_press': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'cable_shoulder_press': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'lever_shoulder_press': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'lever_seated_shoulder_press': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    // Tricep Extensions (inverted)
    'dumbbell_standing_overhead_triceps_extension': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'dumbbell_seated_triceps_extension': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'dumbbells_seated_triceps_extension': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'dumbbell_decline_triceps_extension': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'dumbbell_standing_bent_over_two_arm_triceps_extension': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'dumbbell_standing_triceps_extension': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'dumbbell_standing_one_arm_extension': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'dumbbell_standing_kickback': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'dumbbell_seated_kickback': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'dumbbell_seated_bench_extension': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'barbell_standing_overhead_triceps_extension': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'barbell_lying_triceps_extension_skull_crusher': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'barbell_lying_close_grip_triceps_extension': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'barbell_lying_back_of_the_head_tricep_extension': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'barbell_lying_extension': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'barbell_decline_close_grip_to_skull_press': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'barbell_seated_close_grip_behind_neck_triceps_extension': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'barbell_seated_overhead_triceps_extension': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'barbell_reverse_grip_skullcrusher': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'cable_overhead_triceps_extension': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'cable_high_pulley_overhead_tricep_extension': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'cable_one_arm_tricep_extension': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'cable_incline_triceps_extension': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'cable_kneeling_triceps_extension': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'cable_concentration_extension_on_knee': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'cable_alternate_triceps_extension': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'cable_lying_triceps_extension': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'lever_triceps_extension': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'lever_overhand_triceps_dip': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'smith_machine_incline_tricep_extension': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'ez_barbell_decline_triceps_extension': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'ez_barbell_incline_triceps_extension': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'ez_barbell_seated_triceps_extension': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    // Dips
    'chest_dip': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Push!', 'cueBad': 'Deeper!'}),
    'triceps_dip': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Push!', 'cueBad': 'Deeper!'}),
    'triceps_dips_floor': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Push!', 'cueBad': 'Deeper!'}),
    'weighted_bench_dip': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Push!', 'cueBad': 'Deeper!'}),
    'bench_dip_knees_bent': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Push!', 'cueBad': 'Deeper!'}),
    'wide_grip_chest_dip_on_high_parallel_bars': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Push!', 'cueBad': 'Deeper!'}),
    'reverse_dip': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Push!', 'cueBad': 'Deeper!'}),
    'lever_tricep_dip': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Push!', 'cueBad': 'Deeper!'}),
    'lever_triceps_dip_plate_loaded': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Push!', 'cueBad': 'Deeper!'}),
    // Rows (Squeeze/Open up)
    'barbell_bent_over_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'barbell_incline_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'barbell_rear_delt_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'barbell_reverse_grip_bent_over_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'barbell_reverse_grip_incline_bench_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'barbell_upright_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'ez_bar_reverse_grip_bent_over_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'dumbbell_bent_over_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'dumbbell_incline_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'dumbbell_one_arm_bent_over_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'dumbbell_upright_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'dumbbell_upright_row_back_pov': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'dumbbell_palm_rotational_bent_over_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'dumbbell_reverse_grip_incline_bench_two_arm_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'cable_seated_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'cable_seated_row_bent_bar': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'cable_seated_wide_grip_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'cable_low_seated_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'cable_one_arm_seated_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'cable_elevated_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'cable_straight_back_seated_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'lever_seated_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'lever_high_row_plate_loaded': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'lever_t_bar_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'lever_t_bar_reverse_grip_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'lever_single_arm_neutral_grip_seated_row_plate_loaded': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'lever_neutral_grip_seated_row_plate_loaded': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'lever_row_plate_loaded': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'lever_reverse_grip_vertical_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'lever_reverse_t_bar_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'smith_bent_over_narrow_supinated_grip_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'smith_bent_over_pronated_grip_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'smith_reverse_grip_bent_over_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'smith_upright_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'inverted_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'inverted_row_bent_knees': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'underhand_grip_inverted_back_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'resistance_band_bent_over_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'resistance_band_chest_press': ExerciseConfig(patternType: PatternType.push),
    // Face Pulls/Rear Delts
    'dumbbell_rear_lateral_raise': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'dumbbell_rear_delt_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'dumbbell_rear_delt_fly': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'dumbbell_rear_fly': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'dumbbell_rear_delt_raise': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'lever_seated_reverse_fly': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'cable_supine_reverse_fly': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'cable_rear_delt_fly': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'cable_cross_over_revers_fly': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'cable_seated_rear_lateral_raise': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'cable_crossover': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    // Dumbbell Curls (ONE-ARM — push pattern)
    'dumbbell_standing_biceps_curl': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'dumbbell_alternate_biceps_curl': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'dumbbell_hammer_curl': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'dumbbell_hammer_curl_ii': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'dumbbell_high_curl': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'dumbbell_concentration_curl': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'dumbbell_zottman_curl': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'dumbbell_revers_grip_biceps_curl': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'dumbbell_reverse_preacher_curl': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'dumbbell_seated_revers_grip_concentration_curl': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'dumbbell_seated_bicep_curl': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'dumbbell_seated_hammer_curl': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'dumbbell_standing_concentration_curl': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'dumbbell_standing_inner_biceps_curl': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'dumbbell_standing_inner_biceps_curl_version_2': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'dumbbell_standing_one_arm_concentration_curl': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'dumbbell_peacher_hammer_curl': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'dumbbell_seated_preacher_curl': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    // ═══════════════════════════════════════════════════════════════════════
    // PULL PATTERN — GIF KEYS
    // ═══════════════════════════════════════════════════════════════════════
    'pull_up': ExerciseConfig(patternType: PatternType.pull, params: {'triggerPercent': 0.60, 'resetPercent': 0.85}),
    'chin_up': ExerciseConfig(patternType: PatternType.pull, params: {'triggerPercent': 0.60, 'resetPercent': 0.85}),
    'wide_grip_pull_up': ExerciseConfig(patternType: PatternType.pull, params: {'triggerPercent': 0.60, 'resetPercent': 0.85}),
    'wide_grip_pull_up_on_dip_cage': ExerciseConfig(patternType: PatternType.pull, params: {'triggerPercent': 0.60, 'resetPercent': 0.85}),
    'wide_grip_rear_pull_up': ExerciseConfig(patternType: PatternType.pull, params: {'triggerPercent': 0.60, 'resetPercent': 0.85}),
    'rear_pull_up': ExerciseConfig(patternType: PatternType.pull, params: {'triggerPercent': 0.60, 'resetPercent': 0.85}),
    'pull_up_neutral_grip': ExerciseConfig(patternType: PatternType.pull, params: {'triggerPercent': 0.60, 'resetPercent': 0.85}),
    'shoulder_grip_pull_up': ExerciseConfig(patternType: PatternType.pull, params: {'triggerPercent': 0.60, 'resetPercent': 0.85}),
    'hammer_grip_pull_up_on_dip_cage': ExerciseConfig(patternType: PatternType.pull, params: {'triggerPercent': 0.60, 'resetPercent': 0.85}),
    'cable_bar_lateral_pulldown': ExerciseConfig(patternType: PatternType.pull, params: {'triggerPercent': 0.55, 'resetPercent': 0.85}),
    'cable_pulldown': ExerciseConfig(patternType: PatternType.pull, params: {'triggerPercent': 0.55, 'resetPercent': 0.85}),
    'cable_close_grip_front_lat_pulldown': ExerciseConfig(patternType: PatternType.pull, params: {'triggerPercent': 0.55, 'resetPercent': 0.85}),
    'cable_cross_over_lateral_pulldown': ExerciseConfig(patternType: PatternType.pull, params: {'triggerPercent': 0.55, 'resetPercent': 0.85}),
    'cable_lat_pulldown_full_range_of_motion': ExerciseConfig(patternType: PatternType.pull, params: {'triggerPercent': 0.55, 'resetPercent': 0.85}),
    'cable_incline_pushdown': ExerciseConfig(patternType: PatternType.pull, params: {'triggerPercent': 0.55, 'resetPercent': 0.85}),
    'cable_underhand_pulldown': ExerciseConfig(patternType: PatternType.pull, params: {'triggerPercent': 0.55, 'resetPercent': 0.85}),
    'cable_straight_arm_pulldown': ExerciseConfig(patternType: PatternType.pull, params: {'triggerPercent': 0.55, 'resetPercent': 0.85}),
    'reverse_grip_machine_lat_pulldown': ExerciseConfig(patternType: PatternType.pull, params: {'triggerPercent': 0.55, 'resetPercent': 0.85}),
    'twin_handle_parallel_grip_lat_pulldown': ExerciseConfig(patternType: PatternType.pull, params: {'triggerPercent': 0.55, 'resetPercent': 0.85}),
    'lever_front_pulldown': ExerciseConfig(patternType: PatternType.pull, params: {'triggerPercent': 0.55, 'resetPercent': 0.85}),
    'lever_lateral_pulldown': ExerciseConfig(patternType: PatternType.pull, params: {'triggerPercent': 0.55, 'resetPercent': 0.85}),
    // Shrugs
    'barbell_shrug': ExerciseConfig(patternType: PatternType.pull, params: {'cueGood': 'Shrug!', 'cueBad': 'Higher!'}),
    'dumbbell_shrug': ExerciseConfig(patternType: PatternType.pull, params: {'cueGood': 'Shrug!', 'cueBad': 'Higher!'}),
    'dumbbell_decline_shrug': ExerciseConfig(patternType: PatternType.pull, params: {'cueGood': 'Shrug!', 'cueBad': 'Higher!'}),
    'smith_shrug': ExerciseConfig(patternType: PatternType.pull, params: {'cueGood': 'Shrug!', 'cueBad': 'Higher!'}),
    'cable_shrug': ExerciseConfig(patternType: PatternType.pull, params: {'cueGood': 'Shrug!', 'cueBad': 'Higher!'}),
    'lever_gripless_shrug': ExerciseConfig(patternType: PatternType.pull, params: {'cueGood': 'Shrug!', 'cueBad': 'Higher!'}),
    'lever_gripless_shrug_version_2': ExerciseConfig(patternType: PatternType.pull, params: {'cueGood': 'Shrug!', 'cueBad': 'Higher!'}),
    'lever_shrug_plate_loaded': ExerciseConfig(patternType: PatternType.pull, params: {'cueGood': 'Shrug!', 'cueBad': 'Higher!'}),
    // Kettlebell Swing
    'kettlebell_swing': ExerciseConfig(patternType: PatternType.pull, params: {'triggerPercent': 0.55, 'resetPercent': 0.85}),
    // Pullovers
    'barbell_bent_arm_pullover': ExerciseConfig(patternType: PatternType.pull),
    'barbell_decline_bent_arm_pullover': ExerciseConfig(patternType: PatternType.pull),
    'barbell_decline_pullover': ExerciseConfig(patternType: PatternType.pull),
    'barbell_decline_wide_grip_pullover': ExerciseConfig(patternType: PatternType.pull),
    'dumbbell_pullover': ExerciseConfig(patternType: PatternType.pull),
    'dumbbell_straight_arm_pullover': ExerciseConfig(patternType: PatternType.pull),
    'lever_pullover_plate_loaded': ExerciseConfig(patternType: PatternType.pull),
    'cable_lying_extension_pullover_with_rope_attachment': ExerciseConfig(patternType: PatternType.pull),
    // ═══════════════════════════════════════════════════════════════════════
    // HINGE PATTERN — GIF KEYS
    // ═══════════════════════════════════════════════════════════════════════
    'barbell_good_morning': ExerciseConfig(patternType: PatternType.hinge, params: {'triggerPercent': 0.40, 'resetPercent': 0.75}),
    'barbell_seated_good_morning': ExerciseConfig(patternType: PatternType.hinge, params: {'triggerPercent': 0.40, 'resetPercent': 0.75}),
    'hip_thrusts': ExerciseConfig(patternType: PatternType.hinge, params: {'inverted': true, 'triggerPercent': 0.55}),
    'barbell_hip_thrust': ExerciseConfig(patternType: PatternType.hinge, params: {'inverted': true, 'triggerPercent': 0.55}),
    'barbell_lying_lifting_on_hip': ExerciseConfig(patternType: PatternType.hinge, params: {'inverted': true, 'triggerPercent': 0.55}),
    'hip_raise_bent_knee': ExerciseConfig(patternType: PatternType.hinge, params: {'floor': true, 'cueGood': 'Squeeze!', 'cueBad': 'Hips up!'}),
    'rear_decline_bridge': ExerciseConfig(patternType: PatternType.hinge, params: {'floor': true, 'cueGood': 'Squeeze!', 'cueBad': 'Hips up!'}),
    'lever_standing_rear_kick': ExerciseConfig(patternType: PatternType.hinge, params: {'cueGood': 'Squeeze!', 'cueBad': 'Higher!'}),
    'lever_side_hip_abduction': ExerciseConfig(patternType: PatternType.hinge, params: {'triggerPercent': 0.70}),
    'lever_side_hip_adduction': ExerciseConfig(patternType: PatternType.hinge, params: {'triggerPercent': 0.70}),
    'cable_pull_through': ExerciseConfig(patternType: PatternType.hinge, params: {'triggerPercent': 0.45, 'resetPercent': 0.80}),
    'hyperextension': ExerciseConfig(patternType: PatternType.hinge),
    'hyperextension_on_bench': ExerciseConfig(patternType: PatternType.hinge),
    'hyperextension_version_2': ExerciseConfig(patternType: PatternType.hinge),
    'reverse_hyper_on_flat_bench': ExerciseConfig(patternType: PatternType.hinge),
    'lever_hip_extension_version_2': ExerciseConfig(patternType: PatternType.hinge),
    'lever_standing_hip_extension': ExerciseConfig(patternType: PatternType.hinge),
    // ═══════════════════════════════════════════════════════════════════════
    // CURL PATTERN — GIF KEYS (TWO-ARM)
    // ═══════════════════════════════════════════════════════════════════════
    'barbell_curl': ExerciseConfig(patternType: PatternType.curl),
    'barbell_preacher_curl': ExerciseConfig(patternType: PatternType.curl),
    'barbell_drag_curl': ExerciseConfig(patternType: PatternType.curl),
    'barbell_close_grip_curl': ExerciseConfig(patternType: PatternType.curl),
    'barbell_scott_curl': ExerciseConfig(patternType: PatternType.curl),
    'barbell_standing_concentration_curl': ExerciseConfig(patternType: PatternType.curl),
    'barbell_standing_reverse_grip_curl': ExerciseConfig(patternType: PatternType.curl),
    'barbell_standing_wide_grip_biceps_curl': ExerciseConfig(patternType: PatternType.curl),
    'barbell_reverse_curl': ExerciseConfig(patternType: PatternType.curl),
    'barbell_seated_close_grip_concentration_curl': ExerciseConfig(patternType: PatternType.curl),
    'cable_curl_male': ExerciseConfig(patternType: PatternType.curl),
    'cable_curl_with_multipurpose_v_bar': ExerciseConfig(patternType: PatternType.curl),
    'cable_drag_curl': ExerciseConfig(patternType: PatternType.curl),
    'cable_concentration_curl': ExerciseConfig(patternType: PatternType.curl),
    'cable_rope_hammer_curl': ExerciseConfig(patternType: PatternType.curl),
    'cable_hammer_curl_with_rope_attachment_male': ExerciseConfig(patternType: PatternType.curl),
    'cable_one_arm_curl': ExerciseConfig(patternType: PatternType.curl),
    'cable_one_arm_inner_biceps_curl': ExerciseConfig(patternType: PatternType.curl),
    'cable_overhead_curl': ExerciseConfig(patternType: PatternType.curl),
    'cable_lying_close_grip_curl': ExerciseConfig(patternType: PatternType.curl),
    'cable_biceps_curl_sz_bar': ExerciseConfig(patternType: PatternType.curl),
    'cable_close_grip_curl': ExerciseConfig(patternType: PatternType.curl),
    'ez_barbell_curl': ExerciseConfig(patternType: PatternType.curl),
    'ez_bar_seated_close_grip_concentration_curl': ExerciseConfig(patternType: PatternType.curl),
    'ez_barbell_close_grip_curl': ExerciseConfig(patternType: PatternType.curl),
    'ez_barbell_close_grip_preacher_curl': ExerciseConfig(patternType: PatternType.curl),
    'ez_barbell_reverse_grip_curl': ExerciseConfig(patternType: PatternType.curl),
    'ez_barbell_reverse_grip_preacher_curl': ExerciseConfig(patternType: PatternType.curl),
    'ez_barbell_seated_curls': ExerciseConfig(patternType: PatternType.curl),
    'lever_preacher_curl': ExerciseConfig(patternType: PatternType.curl),
    'lever_preacher_curl_plate_loaded': ExerciseConfig(patternType: PatternType.curl),
    'lever_preacher_curl_version_2': ExerciseConfig(patternType: PatternType.curl),
    'lever_alternate_biceps_curl': ExerciseConfig(patternType: PatternType.curl),
    'lever_bicep_curl': ExerciseConfig(patternType: PatternType.curl),
    'lever_hammer_grip_preacher_curl': ExerciseConfig(patternType: PatternType.curl),
    'lever_reverse_grip_preacher_curl': ExerciseConfig(patternType: PatternType.curl),
    'smith_machine_bicep_curl': ExerciseConfig(patternType: PatternType.curl),
    'resistance_band_bicep_curl': ExerciseConfig(patternType: PatternType.curl),
    // Tricep Pushdown
    'cable_pushdown': ExerciseConfig(patternType: PatternType.curl, params: {'cueGood': 'Push!', 'cueBad': 'Lockout!'}),
    'cable_rope_pushdown': ExerciseConfig(patternType: PatternType.curl, params: {'cueGood': 'Push!', 'cueBad': 'Lockout!'}),
    'cable_triceps_pushdown_sz_bar': ExerciseConfig(patternType: PatternType.curl, params: {'cueGood': 'Push!', 'cueBad': 'Lockout!'}),
    'cable_triceps_pushdown_v_bar_attachment': ExerciseConfig(patternType: PatternType.curl, params: {'cueGood': 'Push!', 'cueBad': 'Lockout!'}),
    'cable_one_arm_side_triceps_pushdown': ExerciseConfig(patternType: PatternType.curl, params: {'cueGood': 'Push!', 'cueBad': 'Lockout!'}),
    'cable_two_arm_tricep_kickback': ExerciseConfig(patternType: PatternType.curl),
    'dumbbell_kickback': ExerciseConfig(patternType: PatternType.curl),
    // Wrist
    'barbell_wrist_curl': ExerciseConfig(patternType: PatternType.curl),
    'barbell_reverse_wrist_curl': ExerciseConfig(patternType: PatternType.curl),
    'barbell_behind_back_finger_curl': ExerciseConfig(patternType: PatternType.curl),
    'barbell_reverse_preacher_curl': ExerciseConfig(patternType: PatternType.curl),
    'barbell_wrist_reverse_curl_version_2': ExerciseConfig(patternType: PatternType.curl),
    'dumbbell_finger_curls': ExerciseConfig(patternType: PatternType.curl),
    'dumbbell_over_bench_one_arm_wrist_curl': ExerciseConfig(patternType: PatternType.curl),
    'dumbbell_over_bench_revers_wrist_curl': ExerciseConfig(patternType: PatternType.curl),
    'dumbbell_over_bench_wrist_curl': ExerciseConfig(patternType: PatternType.curl),
    'dumbbell_seated_neutral_wrist_curl': ExerciseConfig(patternType: PatternType.curl),
    'dumbbell_seated_palms_up_wrist_curl': ExerciseConfig(patternType: PatternType.curl),
    'dumbbell_reverse_wrist_curl': ExerciseConfig(patternType: PatternType.curl),
    'dumbbell_one_arm_reverse_wrist_curl': ExerciseConfig(patternType: PatternType.curl),
    'smith_seated_wrist_curl': ExerciseConfig(patternType: PatternType.curl),
    'lever_gripper_hands_plate_loaded': ExerciseConfig(patternType: PatternType.curl),
    'finger_curls': ExerciseConfig(patternType: PatternType.curl),
    // Lateral/Front Raises
    'dumbbell_lateral_raise': ExerciseConfig(patternType: PatternType.curl),
    'dumbbell_front_raise': ExerciseConfig(patternType: PatternType.curl),
    'dumbbell_standing_alternate_raise': ExerciseConfig(patternType: PatternType.curl),
    'dumbbell_seated_lateral_raise': ExerciseConfig(patternType: PatternType.curl),
    'dumbbell_seated_front_raise': ExerciseConfig(patternType: PatternType.curl),
    'dumbbell_seated_bent_arm_lateral_raise': ExerciseConfig(patternType: PatternType.curl),
    'barbell_front_raise': ExerciseConfig(patternType: PatternType.curl),
    'barbell_front_raise_and_pullover': ExerciseConfig(patternType: PatternType.curl),
    'cable_lateral_raise': ExerciseConfig(patternType: PatternType.curl),
    'cable_one_arm_lateral_raise': ExerciseConfig(patternType: PatternType.curl),
    'cable_front_raise': ExerciseConfig(patternType: PatternType.curl),
    'cable_front_shoulder_raise': ExerciseConfig(patternType: PatternType.curl),
    'lever_lateral_raise': ExerciseConfig(patternType: PatternType.curl),
    'resistance_band_lateral_raise': ExerciseConfig(patternType: PatternType.curl),
    // ═══════════════════════════════════════════════════════════════════════
    // CALF PATTERN — GIF KEYS
    // ═══════════════════════════════════════════════════════════════════════
    'dumbbell_standing_calf_raise': ExerciseConfig(patternType: PatternType.calf),
    'barbell_floor_calf_raise': ExerciseConfig(patternType: PatternType.calf),
    'barbell_standing_leg_calf_raise': ExerciseConfig(patternType: PatternType.calf),
    'bodyweight_standing_calf_raise': ExerciseConfig(patternType: PatternType.calf),
    'lever_standing_calf_raise': ExerciseConfig(patternType: PatternType.calf),
    'lever_seated_calf_raise': ExerciseConfig(patternType: PatternType.calf),
    'lever_calf_press_plate_loaded': ExerciseConfig(patternType: PatternType.calf),
    'lever_calf_raise_bench_press_machine': ExerciseConfig(patternType: PatternType.calf),
    'lever_donkey_calf_raise': ExerciseConfig(patternType: PatternType.calf),
    'lever_rotary_calf': ExerciseConfig(patternType: PatternType.calf),
    'lever_seated_calf_press': ExerciseConfig(patternType: PatternType.calf),
    'lever_seated_calf_raise_plate_loaded': ExerciseConfig(patternType: PatternType.calf),
    'barbell_seated_calf_raise': ExerciseConfig(patternType: PatternType.calf),
    'cable_standing_calf_raise': ExerciseConfig(patternType: PatternType.calf),
    'smith_toe_raise': ExerciseConfig(patternType: PatternType.calf),
    'smith_calf_raise_version_2': ExerciseConfig(patternType: PatternType.calf),
    'smith_reverse_calf_raises': ExerciseConfig(patternType: PatternType.calf),
    'sled_45_degree_calf_press': ExerciseConfig(patternType: PatternType.calf),
    'sled_calf_press_on_leg_press': ExerciseConfig(patternType: PatternType.calf),
    'sled_forward_angled_calf_raise': ExerciseConfig(patternType: PatternType.calf),
    'hack_calf_raise': ExerciseConfig(patternType: PatternType.calf),
    // ═══════════════════════════════════════════════════════════════════════
    // KNEE DRIVE — GIF KEYS
    // ═══════════════════════════════════════════════════════════════════════
    'high_knee_run': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.verticalKnee}),
    'mountain_climber': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.horizontalKnee, 'cueGood': 'Drive!', 'cueBad': 'Knee in!'}),
    'lying_leg_raise': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.legRaise}),
    'hanging_leg_raise': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.legRaise}),
    'hanging_leg_hip_raise': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.legRaise}),
    'hanging_oblique_knee_raise': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.legRaise}),
    'hanging_straight_leg_hip_raise': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.legRaise}),
    'hanging_straight_twisting_leg_hip_raise': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.legRaise}),
    'weighted_hanging_leg_hip_raise': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.legRaise}),
    'vertical_leg_raise_on_parallel_bars': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.legRaise}),
    'seated_leg_raise': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.legRaise}),
    'incline_leg_hip_raise_leg_straight': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.legRaise}),
    'jackknife_sit_up': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.legRaise}),
    'flutter_kicks': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.legRaise, 'triggerThreshold': 0.25, 'resetThreshold': 0.12}),
    'flutter_kicks_version_2': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.legRaise, 'triggerThreshold': 0.25, 'resetThreshold': 0.12}),
    'flutter_kicks_version_3': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.legRaise, 'triggerThreshold': 0.25, 'resetThreshold': 0.12}),
    'bicycle_crunch': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.legRaise, 'cueGood': 'Twist!', 'cueBad': 'Opposite!'}),
    'v_up': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.legRaise, 'cueGood': 'Touch!', 'cueBad': 'Reach!'}),
    'dead_bug': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.legRaise, 'cueGood': 'Extend!', 'cueBad': 'Opposite!'}),
    // ═══════════════════════════════════════════════════════════════════════
    // HOLD PATTERN — GIF KEYS
    // ═══════════════════════════════════════════════════════════════════════
    'front_plank': ExerciseConfig(patternType: PatternType.hold, params: {'holdType': HoldType.plank}),
    'side_plank_male': ExerciseConfig(patternType: PatternType.hold, params: {'holdType': HoldType.plank}),
    // ═══════════════════════════════════════════════════════════════════════
    // CORE PATTERN — GIF KEYS
    // ═══════════════════════════════════════════════════════════════════════
    'crunch_floor_m': ExerciseConfig(patternType: PatternType.core, params: {'trackingMode': 'noseRise', 'triggerThreshold': 10.0, 'resetThreshold': 2.0}),
    'crunch_on_stability_ball': ExerciseConfig(patternType: PatternType.core, params: {'trackingMode': 'noseRise', 'triggerThreshold': 10.0, 'resetThreshold': 2.0}),
    'cross_body_crunch': ExerciseConfig(patternType: PatternType.core, params: {'trackingMode': 'noseRise', 'triggerThreshold': 10.0, 'resetThreshold': 2.0}),
    'tuck_crunch': ExerciseConfig(patternType: PatternType.core, params: {'trackingMode': 'noseRise', 'triggerThreshold': 10.0, 'resetThreshold': 2.0}),
    'cocoons': ExerciseConfig(patternType: PatternType.core, params: {'trackingMode': 'noseRise', 'triggerThreshold': 10.0, 'resetThreshold': 2.0}),
    'elbow_to_knee': ExerciseConfig(patternType: PatternType.core, params: {'trackingMode': 'noseRise', 'triggerThreshold': 10.0, 'resetThreshold': 2.0}),
    'air_bike_m': ExerciseConfig(patternType: PatternType.core, params: {'trackingMode': 'noseRise', 'triggerThreshold': 10.0, 'resetThreshold': 2.0}),
    'reverse_crunch_m': ExerciseConfig(patternType: PatternType.core, params: {'trackingMode': 'noseRise', 'triggerThreshold': 10.0, 'resetThreshold': 2.0}),
    'cable_kneeling_crunch': ExerciseConfig(patternType: PatternType.core, params: {'trackingMode': 'noseRise', 'triggerThreshold': 10.0, 'resetThreshold': 2.0}),
    'cable_tuck_reverse_crunch': ExerciseConfig(patternType: PatternType.core, params: {'trackingMode': 'noseRise', 'triggerThreshold': 10.0, 'resetThreshold': 2.0}),
    'lever_seated_crunch': ExerciseConfig(patternType: PatternType.core, params: {'trackingMode': 'noseRise', 'triggerThreshold': 10.0, 'resetThreshold': 2.0}),
    '3_4_sit_up': ExerciseConfig(patternType: PatternType.core, params: {'trackingMode': 'noseRise', 'triggerThreshold': 20.0, 'resetThreshold': 3.0}),
    'sit_up_ii': ExerciseConfig(patternType: PatternType.core, params: {'trackingMode': 'noseRise', 'triggerThreshold': 20.0, 'resetThreshold': 3.0}),
    'incline_twisting_situp': ExerciseConfig(patternType: PatternType.core, params: {'trackingMode': 'noseRise', 'triggerThreshold': 20.0, 'resetThreshold': 3.0}),
    'incline_twisting_sit_up_version_2': ExerciseConfig(patternType: PatternType.core, params: {'trackingMode': 'noseRise', 'triggerThreshold': 20.0, 'resetThreshold': 3.0}),
    'extra_decline_sit_up': ExerciseConfig(patternType: PatternType.core, params: {'trackingMode': 'noseRise', 'triggerThreshold': 20.0, 'resetThreshold': 3.0}),
    'butt_ups': ExerciseConfig(patternType: PatternType.core, params: {'trackingMode': 'noseRise', 'triggerThreshold': 10.0, 'resetThreshold': 2.0}),
    // ═══════════════════════════════════════════════════════════════════════
    // ROTATION PATTERN — GIF KEYS
    // ═══════════════════════════════════════════════════════════════════════
    'russian_twist_with_medicine_ball': ExerciseConfig(patternType: PatternType.rotation),
    'barbell_standing_twist': ExerciseConfig(patternType: PatternType.rotation),
    'barbell_seated_twist': ExerciseConfig(patternType: PatternType.rotation),
    'barbell_side_bent_ii': ExerciseConfig(patternType: PatternType.rotation),
    'cable_seated_twist': ExerciseConfig(patternType: PatternType.rotation),
    'cable_twist': ExerciseConfig(patternType: PatternType.rotation),
    'cable_horizontal_pallof_press': ExerciseConfig(patternType: PatternType.rotation),
    'cable_standing_lift': ExerciseConfig(patternType: PatternType.rotation),
    'cable_twisting_overhead_press': ExerciseConfig(patternType: PatternType.rotation),
    'cable_side_bend': ExerciseConfig(patternType: PatternType.rotation),
    'dumbbell_side_bend': ExerciseConfig(patternType: PatternType.rotation),
    'spine_twist': ExerciseConfig(patternType: PatternType.rotation),
    'wipers_straight_leg': ExerciseConfig(patternType: PatternType.rotation),
    'half_wipers_bent_leg': ExerciseConfig(patternType: PatternType.rotation),
    'kettlebell_windmill': ExerciseConfig(patternType: PatternType.rotation),
    'lever_seated_twist': ExerciseConfig(patternType: PatternType.rotation),
    // ═══════════════════════════════════════════════════════════════════════
    // SPECIAL — GIF KEYS (timer/hold/misc)
    // ═══════════════════════════════════════════════════════════════════════
    'standing_wheel_rollout': ExerciseConfig(patternType: PatternType.push),
    'skipping_rope': ExerciseConfig(patternType: PatternType.calf),
    'stationary_bike_run_version_3': ExerciseConfig(patternType: PatternType.hold, params: {'holdType': HoldType.plank}),
    'cable_standing_fly': ExerciseConfig(patternType: PatternType.push),
    'cable_hip_adduction': ExerciseConfig(patternType: PatternType.hinge, params: {'triggerPercent': 0.70}),
    'lever_seated_hip_abduction': ExerciseConfig(patternType: PatternType.hinge, params: {'triggerPercent': 0.70}),
    'lever_seated_hip_adduction': ExerciseConfig(patternType: PatternType.hinge, params: {'triggerPercent': 0.70}),
    'standing_hip_flexor': ExerciseConfig(patternType: PatternType.hold, params: {'holdType': HoldType.plank}),
    'cable_seated_shoulder_internal_rotation': ExerciseConfig(patternType: PatternType.hold, params: {'holdType': HoldType.plank}),
    'dumbbell_upright_shoulder_external_rotation': ExerciseConfig(patternType: PatternType.hold, params: {'holdType': HoldType.plank}),
    'weighted_lying_neck_extension': ExerciseConfig(patternType: PatternType.hold, params: {'holdType': HoldType.plank}),
    'weighted_lying_neck_extension_with_head_harness': ExerciseConfig(patternType: PatternType.hold, params: {'holdType': HoldType.plank}),
    'weighted_lying_neck_flexion': ExerciseConfig(patternType: PatternType.hold, params: {'holdType': HoldType.plank}),
    'weighted_lying_neck_flexion_with_head_harness': ExerciseConfig(patternType: PatternType.hold, params: {'holdType': HoldType.plank}),
    'weighted_lying_side_lifting_head_with_head_harness': ExerciseConfig(patternType: PatternType.hold, params: {'holdType': HoldType.plank}),
    'weighted_seated_neck_extension_with_head_harness': ExerciseConfig(patternType: PatternType.hold, params: {'holdType': HoldType.plank}),
    'weighted_standing_neck_extension_with_head_harness': ExerciseConfig(patternType: PatternType.hold, params: {'holdType': HoldType.plank}),
    'cable_seated_neck_extension_with_head_harness': ExerciseConfig(patternType: PatternType.hold, params: {'holdType': HoldType.plank}),
    'cable_seated_neck_flexion_with_head_harness': ExerciseConfig(patternType: PatternType.hold, params: {'holdType': HoldType.plank}),
    'lever_neck_extension_plate_loaded': ExerciseConfig(patternType: PatternType.hold, params: {'holdType': HoldType.plank}),
    'lever_neck_left_side_flexion_plate_loaded': ExerciseConfig(patternType: PatternType.hold, params: {'holdType': HoldType.plank}),
    'lever_neck_right_side_flexion_plate_loaded': ExerciseConfig(patternType: PatternType.hold, params: {'holdType': HoldType.plank}),
    // ═══════════════════════════════════════════════════════════════════════
    // ██ SECTION 2: HOME/CAMERA EXERCISES
    // ██ Keep old IDs for camera tracking. Override maps them to GIFs.
    // ═══════════════════════════════════════════════════════════════════════
    // SQUAT — Home
    'squat': ExerciseConfig(patternType: PatternType.squat),
    'air_squat': ExerciseConfig(patternType: PatternType.squat),
    'bodyweight_squat': ExerciseConfig(patternType: PatternType.squat),
    'goblet_squat': ExerciseConfig(patternType: PatternType.squat),
    'barbell_squat': ExerciseConfig(patternType: PatternType.squat),
    'barbell_back_squat': ExerciseConfig(patternType: PatternType.squat),
    'back_squat': ExerciseConfig(patternType: PatternType.squat),
    'front_squat': ExerciseConfig(patternType: PatternType.squat),
    'sumo_squat': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.75}),
    'hack_squat': ExerciseConfig(patternType: PatternType.squat),
    'overhead_squat': ExerciseConfig(patternType: PatternType.squat),
    'zercher_squat': ExerciseConfig(patternType: PatternType.squat),
    'sissy_squat': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.70}),
    'spanish_squat': ExerciseConfig(patternType: PatternType.squat),
    'squat_pulse': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.80, 'resetPercent': 0.85}),
    'sumo_squat_pulse': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.80, 'resetPercent': 0.85}),
    'sumo_squat_hold_pulse': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.80, 'resetPercent': 0.85}),
    'banded_squat': ExerciseConfig(patternType: PatternType.squat),
    'banded_lateral_walk': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.90}),
    'squat_to_kickback': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.78}),
    'squat_press': ExerciseConfig(patternType: PatternType.squat),
    'thruster': ExerciseConfig(patternType: PatternType.squat),
    'squat_reach': ExerciseConfig(patternType: PatternType.squat),
    'pistol_squat': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.70}),
    'lunge': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.78, 'resetPercent': 0.88}),
    'walking_lunge': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.78, 'resetPercent': 0.88}),
    'reverse_lunge': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.78, 'resetPercent': 0.88}),
    'static_lunge': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.78, 'resetPercent': 0.88}),
    'deficit_reverse_lunge': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.78, 'resetPercent': 0.88}),
    'curtsy_lunge': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.78, 'resetPercent': 0.88}),
    'pulse_curtsy_lunge': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.80, 'resetPercent': 0.85}),
    'lateral_lunge': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.80, 'resetPercent': 0.88}),
    'split_squat': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.78, 'resetPercent': 0.88}),
    'bulgarian_split_squat': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.78, 'resetPercent': 0.88}),
    'jump_lunge': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.78, 'resetPercent': 0.86}),
    'jumping_jack': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.90}),
    'tuck_jump': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.80}),
    'star_jump': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.85}),
    'lateral_hop': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.85}),
    'skater_hop': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.80}),
    'box_jump': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.75}),
    'leg_press': ExerciseConfig(patternType: PatternType.squat, params: {'triggerPercent': 0.75}),
    'leg_extension': ExerciseConfig(patternType: PatternType.squat),
    'leg_curl': ExerciseConfig(patternType: PatternType.squat),
    'hamstring_curl': ExerciseConfig(patternType: PatternType.squat),
    'lying_leg_curl': ExerciseConfig(patternType: PatternType.squat),
    'seated_leg_curl': ExerciseConfig(patternType: PatternType.squat),
    'nordic_curl': ExerciseConfig(patternType: PatternType.squat),
    'step_up': ExerciseConfig(patternType: PatternType.stepUp, params: {'cueGood': 'Up!', 'cueBad': 'Drive!'}),
    // PUSH — Home
    'pushup': ExerciseConfig(patternType: PatternType.push),
    'push_up': ExerciseConfig(patternType: PatternType.push),
    'incline_pushup': ExerciseConfig(patternType: PatternType.push),
    'incline_push_up': ExerciseConfig(patternType: PatternType.push),
    'wall_push_up': ExerciseConfig(patternType: PatternType.push),
    'decline_pushup': ExerciseConfig(patternType: PatternType.push),
    'decline_push_up': ExerciseConfig(patternType: PatternType.push),
    'wide_pushup': ExerciseConfig(patternType: PatternType.push),
    'diamond_pushup': ExerciseConfig(patternType: PatternType.push),
    'close_grip_pushup': ExerciseConfig(patternType: PatternType.push),
    'pike_pushup': ExerciseConfig(patternType: PatternType.push),
    'archer_pushup': ExerciseConfig(patternType: PatternType.push),
    'clap_pushup': ExerciseConfig(patternType: PatternType.push),
    'plank_to_pushup': ExerciseConfig(patternType: PatternType.push),
    'bench_press': ExerciseConfig(patternType: PatternType.push),
    'incline_press': ExerciseConfig(patternType: PatternType.push),
    'decline_press': ExerciseConfig(patternType: PatternType.push),
    'close_grip_bench_press': ExerciseConfig(patternType: PatternType.push),
    'machine_chest_press': ExerciseConfig(patternType: PatternType.push),
    'chest_fly': ExerciseConfig(patternType: PatternType.push),
    'pec_deck': ExerciseConfig(patternType: PatternType.push),
    'overhead_press': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'shoulder_press': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'military_press': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'arnold_press': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'push_press': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'dip': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Push!', 'cueBad': 'Deeper!'}),
    'tricep_dip': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Push!', 'cueBad': 'Deeper!'}),
    'bench_dip': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Push!', 'cueBad': 'Deeper!'}),
    'tricep_extension': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'overhead_tricep_extension': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'skull_crusher': ExerciseConfig(patternType: PatternType.push, params: {'inverted': true}),
    'face_pull': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'reverse_fly': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'rear_delt_fly': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'dumbbell_curl': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'hammer_curl': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'concentration_curl': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'barbell_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'dumbbell_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'cable_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'seated_cable_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'tbar_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'pendlay_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'upright_row': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'lateral_raise': ExerciseConfig(patternType: PatternType.curl),
    'front_raise': ExerciseConfig(patternType: PatternType.curl),
    // PULL — Home
    'pullup': ExerciseConfig(patternType: PatternType.pull, params: {'triggerPercent': 0.60, 'resetPercent': 0.85}),
    'chinup': ExerciseConfig(patternType: PatternType.pull, params: {'triggerPercent': 0.60, 'resetPercent': 0.85}),
    'lat_pulldown': ExerciseConfig(patternType: PatternType.pull, params: {'triggerPercent': 0.55, 'resetPercent': 0.85}),
    'shrug': ExerciseConfig(patternType: PatternType.pull, params: {'cueGood': 'Shrug!', 'cueBad': 'Higher!'}),
    // HINGE — Home
    'deadlift': ExerciseConfig(patternType: PatternType.squat),
    'romanian_deadlift': ExerciseConfig(patternType: PatternType.squat),
    'rdl': ExerciseConfig(patternType: PatternType.squat),
    'dumbbell_rdl': ExerciseConfig(patternType: PatternType.squat),
    'stiff_leg_deadlift': ExerciseConfig(patternType: PatternType.squat),
    'sumo_deadlift': ExerciseConfig(patternType: PatternType.squat),
    'single_leg_deadlift': ExerciseConfig(patternType: PatternType.squat),
    'single_leg_rdl': ExerciseConfig(patternType: PatternType.squat),
    'single_leg_rdl_pulse': ExerciseConfig(patternType: PatternType.hinge, params: {'triggerPercent': 0.35}),
    'trap_bar_deadlift': ExerciseConfig(patternType: PatternType.squat),
    'good_morning': ExerciseConfig(patternType: PatternType.hinge, params: {'triggerPercent': 0.40, 'resetPercent': 0.75}),
    'kettlebell_swings': ExerciseConfig(patternType: PatternType.pull, params: {'triggerPercent': 0.55, 'resetPercent': 0.85}),
    'kb_swing': ExerciseConfig(patternType: PatternType.pull, params: {'triggerPercent': 0.55, 'resetPercent': 0.85}),
    'back_extension': ExerciseConfig(patternType: PatternType.hinge),
    'reverse_hyper': ExerciseConfig(patternType: PatternType.hinge),
    'hip_thrust': ExerciseConfig(patternType: PatternType.hinge, params: {'inverted': true, 'triggerPercent': 0.55}),
    'glute_bridge': ExerciseConfig(patternType: PatternType.hinge, params: {'floor': true, 'cueGood': 'Squeeze!', 'cueBad': 'Hips up!'}),
    'single_leg_glute_bridge': ExerciseConfig(patternType: PatternType.hinge, params: {'floor': true, 'cueGood': 'Squeeze!', 'cueBad': 'Hips up!'}),
    'elevated_glute_bridge': ExerciseConfig(patternType: PatternType.hinge, params: {'floor': true, 'cueGood': 'Squeeze!', 'cueBad': 'Hips up!'}),
    'banded_glute_bridge': ExerciseConfig(patternType: PatternType.hinge, params: {'floor': true, 'cueGood': 'Squeeze!', 'cueBad': 'Hips up!'}),
    'glute_bridge_hold': ExerciseConfig(patternType: PatternType.hold, params: {'holdType': HoldType.plank}),
    'frog_pump': ExerciseConfig(patternType: PatternType.hinge, params: {'floor': true, 'cueGood': 'Squeeze!', 'cueBad': 'Hips up!'}),
    'frog_pump_pulse': ExerciseConfig(patternType: PatternType.hinge, params: {'floor': true, 'cueGood': 'Squeeze!', 'cueBad': 'Hips up!'}),
    'frog_pump_hold_pulse': ExerciseConfig(patternType: PatternType.hinge, params: {'floor': true, 'cueGood': 'Squeeze!', 'cueBad': 'Hips up!'}),
    'standing_glute_squeeze': ExerciseConfig(patternType: PatternType.hinge, params: {'inverted': true}),
    'quadruped_hip_extension': ExerciseConfig(patternType: PatternType.hinge, params: {'cueGood': 'Squeeze!', 'cueBad': 'Higher!'}),
    'quadruped_hip_extension_pulse': ExerciseConfig(patternType: PatternType.hinge, params: {'triggerPercent': 0.40}),
    'donkey_kick': ExerciseConfig(patternType: PatternType.hinge, params: {'cueGood': 'Squeeze!', 'cueBad': 'Higher!'}),
    'donkey_kick_pulse': ExerciseConfig(patternType: PatternType.hinge, params: {'triggerPercent': 0.40}),
    'donkey_kicks_cable': ExerciseConfig(patternType: PatternType.hinge, params: {'triggerPercent': 0.55}),
    'fire_hydrant': ExerciseConfig(patternType: PatternType.hinge, params: {'triggerPercent': 0.70}),
    'banded_fire_hydrant': ExerciseConfig(patternType: PatternType.hinge, params: {'triggerPercent': 0.70}),
    'banded_clamshell': ExerciseConfig(patternType: PatternType.hinge, params: {'triggerPercent': 0.70}),
    'side_lying_leg_raise': ExerciseConfig(patternType: PatternType.hinge, params: {'triggerPercent': 0.75}),
    // CALF — Home (includes kickbacks)
    'glute_kickback': ExerciseConfig(patternType: PatternType.calf, params: {'cueGood': 'Squeeze!', 'cueBad': 'Kick back!'}),
    'cable_kickback': ExerciseConfig(patternType: PatternType.calf, params: {'cueGood': 'Squeeze!', 'cueBad': 'Kick back!'}),
    'standing_glute_kickback': ExerciseConfig(patternType: PatternType.calf, params: {'cueGood': 'Squeeze!', 'cueBad': 'Kick back!'}),
    'banded_kickback': ExerciseConfig(patternType: PatternType.calf, params: {'cueGood': 'Squeeze!', 'cueBad': 'Kick back!'}),
    'calf_raise': ExerciseConfig(patternType: PatternType.calf),
    'standing_calf_raise': ExerciseConfig(patternType: PatternType.calf),
    'seated_calf_raise': ExerciseConfig(patternType: PatternType.calf),
    'single_leg_calf_raise': ExerciseConfig(patternType: PatternType.calf),
    'jump_rope': ExerciseConfig(patternType: PatternType.calf),
    // CURL — Home
    'curl': ExerciseConfig(patternType: PatternType.curl),
    'bicep_curl': ExerciseConfig(patternType: PatternType.curl),
    'preacher_curl': ExerciseConfig(patternType: PatternType.curl),
    'spider_curl': ExerciseConfig(patternType: PatternType.curl),
    'cable_curl': ExerciseConfig(patternType: PatternType.curl),
    'ez_bar_curl': ExerciseConfig(patternType: PatternType.curl),
    'reverse_curl': ExerciseConfig(patternType: PatternType.curl),
    'zottman_curl': ExerciseConfig(patternType: PatternType.push, params: {'cueGood': 'Squeeze!', 'cueBad': 'Open up!'}),
    'tricep_pushdown': ExerciseConfig(patternType: PatternType.curl, params: {'cueGood': 'Push!', 'cueBad': 'Lockout!'}),
    'rope_pushdown': ExerciseConfig(patternType: PatternType.curl),
    'tricep_kickback': ExerciseConfig(patternType: PatternType.curl),
    'wrist_curl': ExerciseConfig(patternType: PatternType.curl),
    // KNEE DRIVE — Home (all modes)
    'high_knee': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.verticalKnee}),
    'high_knees': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.verticalKnee}),
    'high_knee_sprint': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.verticalKnee}),
    'marching_in_place': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.verticalKnee}),
    'running_in_place': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.verticalKnee}),
    'knee_tap': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.verticalKnee}),
    'a_skip': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.verticalKnee}),
    'b_skip': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.verticalKnee}),
    'step_touch': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.verticalKnee}),
    'side_step': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.verticalKnee}),
    'lateral_shuffle': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.verticalKnee}),
    'skater': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.verticalKnee}),
    'mountain_climbers': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.horizontalKnee}),
    'mountain_climber_crossover': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.horizontalKnee, 'cueGood': 'Cross!', 'cueBad': 'Knee across!'}),
    'leg_raise': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.legRaise}),
    'hanging_leg_raises': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.legRaise}),
    'v_ups': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.legRaise, 'cueGood': 'Touch!', 'cueBad': 'Reach!'}),
    'bicycle_crunches': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.legRaise}),
    'flutter_kick': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.legRaise, 'triggerThreshold': 0.25, 'resetThreshold': 0.12}),
    'scissor_kick': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.legRaise, 'triggerThreshold': 0.25, 'resetThreshold': 0.12}),
    'dead_bugs': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.legRaise}),
    'butt_kick': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.buttKick, 'cueGood': 'Snap!', 'cueBad': 'Heels up!'}),
    'butt_kicks': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.buttKick, 'cueGood': 'Snap!', 'cueBad': 'Heels up!'}),
    'butt_kick_sprint': ExerciseConfig(patternType: PatternType.kneeDrive, params: {'mode': KneeDriveMode.buttKick, 'cueGood': 'Fast!', 'cueBad': 'Heels up!'}),
    // HOLD — Home
    'plank': ExerciseConfig(patternType: PatternType.hold, params: {'holdType': HoldType.plank}),
    'forearm_plank': ExerciseConfig(patternType: PatternType.hold, params: {'holdType': HoldType.plank}),
    'high_plank': ExerciseConfig(patternType: PatternType.hold, params: {'holdType': HoldType.plank}),
    'side_plank': ExerciseConfig(patternType: PatternType.hold, params: {'holdType': HoldType.plank}),
    'plank_jack': ExerciseConfig(patternType: PatternType.hold, params: {'holdType': HoldType.plank}),
    'plank_tap': ExerciseConfig(patternType: PatternType.hold, params: {'holdType': HoldType.plank}),
    'bird_dog': ExerciseConfig(patternType: PatternType.hold, params: {'holdType': HoldType.plank}),
    'hollow_body_hold': ExerciseConfig(patternType: PatternType.hold, params: {'holdType': HoldType.plank}),
    'l_sit': ExerciseConfig(patternType: PatternType.hold, params: {'holdType': HoldType.plank}),
    'superman': ExerciseConfig(patternType: PatternType.hold, params: {'holdType': HoldType.plank}),
    'superman_hold': ExerciseConfig(patternType: PatternType.hold, params: {'holdType': HoldType.plank}),
    'wall_sit': ExerciseConfig(patternType: PatternType.hold, params: {'holdType': HoldType.wallSit}),
    'dead_hang': ExerciseConfig(patternType: PatternType.hold, params: {'holdType': HoldType.hang}),
    // CORE — Home
    'crunch': ExerciseConfig(patternType: PatternType.core, params: {'trackingMode': 'noseRise', 'triggerThreshold': 10.0, 'resetThreshold': 2.0}),
    'sit_up': ExerciseConfig(patternType: PatternType.core, params: {'trackingMode': 'noseRise', 'triggerThreshold': 20.0, 'resetThreshold': 3.0}),
    'cable_crunch': ExerciseConfig(patternType: PatternType.core, params: {'trackingMode': 'noseRise', 'triggerThreshold': 10.0, 'resetThreshold': 2.0}),
    // ROTATION — Home
    'russian_twist': ExerciseConfig(patternType: PatternType.rotation),
    'wood_chop': ExerciseConfig(patternType: PatternType.rotation),
    'cable_wood_chop': ExerciseConfig(patternType: PatternType.rotation),
    'windmill': ExerciseConfig(patternType: PatternType.rotation),
    'pallof_press': ExerciseConfig(patternType: PatternType.rotation),
    'seated_twist': ExerciseConfig(patternType: PatternType.rotation),
    'oblique_crunch': ExerciseConfig(patternType: PatternType.rotation),
  };
}
